dm9(x)0: fix build dm920: ERROR: Nothing RPROVIDES 'kernel-3.14-1.17-dm900 (but /home/hains/test/openpli-oe-core/meta-dream/ recipes-bsp/drivers/dreambox-dvb-modules-dm920_3.14-1.17-20170801.bb RDEPENDS on or otherwise requires it)
dm900:
ERROR: Nothing RPROVIDES 'dreambox-secondstage-dm900' (but /home/hains/test1/openpli-oe-core/meta-dream/recipes-bsp
/drivers/dreambox-dvb-modules-dm900_3.14-1.17-20170801.bb RDEPENDS on or otherwise requires it)