kernel-3.2: fix build with gcc7 Use '!' instead of '~'.
dm8000/kernel-source/arch/mips/math-emu/cp1emu.c:200:38: error: '~'
on a boolean expression [-Werror=bool-operation]
|  #define DITOREG(di, x) (ctx->fpr[x & ~(cop1_64bit(xcp) == 0)] = (di))